# Copyright (c) 2024, WSO2 LLC. (https://www.wso2.com/) All Rights Reserved.

# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

openapi: 3.0.2
info:
  title: File Upload - Python REST API
  description: API for processing text, PDFs, images, and Word documents to generate
    mapping instructions or records
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 0.1.0
servers:
  - url: http://localhost:8000
paths:
  /file_upload/generate_mapping_instruction:
    post:
      tags:
      - generate-mapping-instruction
      summary: Generate Mapping Instruction
      operationId: File_upload_generate_mapping_instruction_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_File_upload_generate_mapping_instruction_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /file_upload/generate_record:
    post:
      tags:
      - generate-record
      summary: Generate Record
      operationId: File_upload_generate_record_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_File_upload_generate_record_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_File_upload_generate_mapping_instruction_post:
      properties:
        file:
          type: string
          format: binary
          title: File
        text:
          type: string
          title: Text
      type: object
      title: Body_File_upload_generate_mapping_instruction_post
    Body_File_upload_generate_record_post:
      properties:
        file:
          type: string
          format: binary
          title: File
        text:
          type: string
          title: Text
      type: object
      title: Body_File_upload_generate_record_post
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError


